# Generated by Django 4.1.5 on 2023-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='maa@gamil.com', max_length=254),
        ),
    ]
